### PR TITLE
Create test

### PR DESCRIPTION
**Pull request by jacek-lewandowski**

### CODE REVIEW

**Comment by jacek-lewandowski** [comment]
test CqlTest

**Comment by jtgrabowski** [comment]
test CqlTest

**Comment by jacek-lewandowski** [comment]
test CqlTest

**Comment by jacek-lewandowski** [comment]
test CqlTest

**Comment by jacek-lewandowski** [comment]
asdfasdf

**Comment by jacek-lewandowski** [comment]
asdfasdf

**Comment by jacek-lewandowski** [comment]
gasdfasdfa

**Comment by jacek-lewandowski** [comment]
asdfasdfa

**Pull request merged**
